version: '3'

services:
  s3:
    image: minio/minio
    ports:
      - "9010:9010"
      - "9011:9011"
    network_mode: host
    environment:
      MINIO_ROOT_USER       : accesskey
      MINIO_ROOT_PASSWORD   : secretkey
      MINIO_ADDRESS         : ':9010'
      MINIO_CONSOLE_ADDRESS : ':9011'
    command: minio server /var/lib/data
    volumes:
      - ./data/s3:/var/lib/data

  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    depends_on:
      - s3
    environment:
      # S3 config
      S3_ENDPOINT   : localhost:9010
      S3_ACCESS_KEY : accesskey
      S3_SECRET_KEY : secretkey
      S3_SECURE     : false
      S3_BUCKET     : prod-nlp-chatbot
    volumes:
      - ./src:/src
    network_mode: host

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - s3
    environment:
      # S3 config
      S3_ENDPOINT   : localhost:9010
      S3_ACCESS_KEY : accesskey
      S3_SECRET_KEY : secretkey
      S3_SECURE     : false
      S3_BUCKET     : dev-nlp-chatbot
    ports:
      - "8002:8002"
    volumes:
      - ./src:/src
    network_mode: host

volumes:
  s3-data:
